name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Get deps
      run: go get -v ./...

    - name: Get tests deps
      run: go get -v github.com/stretchr/testify

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
